### ISSUE TITLE
Race Bio

### ISSUE THREAD

**Issue by isaacharris** [baclevenger/spacegame#12]
Write a paragraph or two Bio for each race, giving the name, what they are good at, bad at, and what resources they require. Include creative background history and a summary of the race as a whole (peaceful, hostile, lazy, tricky ect). Be creative!!

**Comment by ekerns96** [comment]
So you don't want to do a race bio anymore?

**Comment by ekerns96** [comment]
Where do you want the Bios to be? Drive or on here somewhere?

**Comment by ekerns96** [comment]
Where do you want the Bios stored?

**Comment by jakefist** [comment]
Google Drive will be fine for now.

On Wed, Feb 25, 2015 at 9:02 AM, ekerns96 notifications@github.com wrote:

> Where do you want the Bios stored?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baclevenger/spacegame/issues/12#issuecomment-75963968
> .

## 

And that's my half a nickel. (Seriously. Cut in half with, like, freaking
tin-snips or something.)

" When in danger when in doubt,
  Run in circles, scream and shout"
