### ISSUE TITLE
Compile basic resource lists

### ISSUE THREAD

**Issue by jakefist** [baclevenger/spacegame#3]
@isaacharris  This will be for all basic resources.

**Comment by jakefist** [comment]
Lets get our existing resources listed in the comments here. @isaacharris

**Comment by amyers1997** [comment]
Energy
Oxygen
Water
Food
minerals
Dark Mater (premium)

**Comment by jakefist** [comment]
Where we going to add currency?

On Thu, Feb 12, 2015 at 10:52 AM, amyers1997 notifications@github.com
wrote:

> Energy
> Oxygen
> Water
> Food
> minerals
> Dark Mater (premium)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baclevenger/spacegame/issues/3#issuecomment-74094283.

## 

And that's my half a nickel. (Seriously. Cut in half with, like, freaking
tin-snips or something.)

" When in danger when in doubt,
  Run in circles, scream and shout"

**Comment by ekerns96** [comment]
Galactic currency
